# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('like', models.IntegerField(verbose_name=b'Comment Likes')),
                ('body', models.TextField(blank=True, verbose_name=b'Comment body')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200, null=True, verbose_name=b'City')),
                ('country', models.CharField(max_length=200, verbose_name=b'Country')),
            ],
        ),
        migrations.CreateModel(
            name='Look',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('hype', models.IntegerField(default=0, verbose_name=b'Site hype')),
                ('title', models.TextField(blank=True, verbose_name=b'Look title')),
                ('img_url', models.URLField(verbose_name=b'Location of look img')),
                ('desc', models.TextField(blank=True, verbose_name=b'Look description')),
                ('orig_id', models.IntegerField(unique=True, verbose_name=b'Original lookbook id')),
                ('orig_hype', models.IntegerField(default=0, verbose_name=b'Original hype rating')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='looks', to='looksdigest.Location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set([('city', 'country')]),
        ),
        migrations.AddField(
            model_name='comment',
            name='look',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='looksdigest.Look'),
        ),
    ]
