# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 15:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('looksdigest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='look',
            name='orig_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name=b'Original creation dates'),
        ),
    ]
