# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-31 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('looksdigest', '0002_look_orig_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='look',
            name='orig_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name=b'Original creation dates'),
        ),
    ]
